name: CI/CD Local Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t set4-app:latest ./app

      # 4️⃣ Enable kind (Docker-based Kubernetes) to simulate Docker Desktop
      - name: Set up kind
        uses: engineerd/setup-kind@v0.7.0
        with:
          version: v0.20.0

      # 5️⃣ Load Docker image into kind cluster
      - name: Load Image into Kubernetes
        run: |
          kind load docker-image set4-app:latest

      # 6️⃣ Apply manifests
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f deployment/deployment.yaml --validate=false

      # 7️⃣ Wait for Deployment
      - name: Wait for Deployment
        run: |
          kubectl rollout status deployment/set4-deployment --timeout=120s

      # 8️⃣ Test service is running
      - name: Test Pod Status
        run: |
          kubectl get pods
          kubectl get svc
